---
abstract: 'Interface to genealogy GEDCOM files'
author:
  - 'Paul Johnson (paul@pjcj.net)'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gedcom
no_index:
  directory:
    - t
    - inc
recommends:
  Date::Manip: 0
  Parse::RecDescent: 0
  Roman: 0
resources:
  X_mailing_list: http://lists.perl.org/list/perl-gedcom.html
  bugtracker: https://github.com/pjcj/Gedcom.pm/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/pjcj/Gedcom.pm
version: 1.19
